development: &development
  adapter      : postgresql
  encoding     : unicode
  host         : localhost
  database     : <%= ENV.fetch('APP_NAME', 'fufortune') %>_dev
  timeout      : 5000
  pool         : 5
  min_messages : warning
  prepared_statements: false

test: &test
  <<: *development
  database     : <%= ENV.fetch('APP_NAME', 'fufortune') %>_test

staging: &production
  <<: *development
  database     : <%= ENV.fetch('APP_NAME', 'fufortune') %>_staging

production: &production
  <<: *development
  database     : <%= ENV.fetch('APP_NAME', 'fufortune') %>_alpha
